export const _topics = [
  "Accounting",
  "Advertising",
  "Aerospace",
  "Agriculture",
  "Architecture",
  "Banking",
  "Technology",
  "Other",
  "Utilities",
];

export interface Topic {
  name: string;
  subtopics?: Topic[];
}

export const topics = [
  {
    name: "Agriculture",
    subtopics: [
      { name: "Crop Production" },
      { name: "Livestock Management" },
      { name: "Horticulture" },
      { name: "Agricultural Technology" },
      { name: "Soil Science" },
      { name: "Agribusiness" },
    ],
  },
  {
    name: "Arts and Humanities",
    subtopics: [
      { name: "Visual Arts" },
      { name: "Performing Arts" },
      { name: "History" },
      { name: "Literature" },
      { name: "Philosophy" },
      { name: "Languages" },
    ],
  },
  {
    name: "Business and Finance",
    subtopics: [
      { name: "Accounting" },
      { name: "Marketing" },
      { name: "Human Resources" },
      { name: "Management" },
      { name: "Entrepreneurship" },
      { name: "Investment" },
    ],
  },
  {
    name: "Computer Science",
    subtopics: [
      {
        name: "Programming Languages",
        subtopics: [
          { name: "Python" },
          { name: "JavaScript" },
          { name: "Java" },
          { name: "C++" },
          { name: "C#" },
          { name: "Ruby" },
          { name: "PHP" },
          { name: "Swift" },
          { name: "Kotlin" },
          { name: "TypeScript" },
          { name: "Go" },
          { name: "Rust" },
          { name: "R" },
          { name: "MATLAB" },
          { name: "Scala" },
          { name: "Lua" },
          { name: "Shell Scripting" },
        ],
      },
      {
        name: "Web Development",
        subtopics: [
          {
            name: "HTML",
            subtopics: [
              { name: "HTML5" },
              { name: "Semantic HTML" },
              { name: "HTML Forms" },
            ],
          },
          {
            name: "CSS",
            subtopics: [
              { name: "CSS3" },
              { name: "Flexbox" },
              { name: "CSS Grid" },
              { name: "Responsive Design" },
              { name: "SASS" },
              { name: "LESS" },
              { name: "PostCSS" },
              { name: "CSS-in-JS" },
              { name: "Tailwind CSS" },
            ],
          },
          {
            name: "JavaScript",
            subtopics: [
              { name: "ES6+" },
              { name: "TypeScript" },
              { name: "jQuery" },
              { name: "Node.js" },
            ],
          },
          {
            name: "Front-end Frameworks",
            subtopics: [
              { name: "React.js" },
              { name: "Angular.js" },
              { name: "Vue.js" },
              { name: "Svelte" },
            ],
          },
          {
            name: "Back-end Frameworks",
            subtopics: [
              { name: "Express.js" },
              { name: "Django" },
              { name: "Ruby on Rails" },
              { name: "Laravel" },
              { name: "Spring Boot" },
            ],
          },
          {
            name: "Databases",
            subtopics: [
              { name: "SQL" },
              { name: "MySQL" },
              { name: "PostgreSQL" },
              { name: "MongoDB" },
              { name: "NoSQL" },
              { name: "Firebase" },
            ],
          },
          {
            name: "Web Servers",
            subtopics: [
              { name: "Apache" },
              { name: "Nginx" },
              { name: "IIS" },
              { name: "Node.js as a web server" },
            ],
          },
          {
            name: "Web Performance Optimization",
            subtopics: [
              { name: "Minification" },
              { name: "Bundling" },
              { name: "Caching" },
              { name: "Lazy Loading" },
              { name: "Critical Render Path" },
              { name: "Progressive Web Apps" },
            ],
          },
          {
            name: "Web Accessibility",
            subtopics: [
              { name: "Semantic HTML" },
              { name: "ARIA" },
              { name: "WCAG" },
              { name: "Inclusive Design" },
            ],
          },
          {
            name: "Web Accessibility",
            subtopics: [
              { name: "Semantic HTML" },
              { name: "ARIA" },
              { name: "WCAG" },
              { name: "Inclusive Design" },
              { name: "Color Contrast" },
              { name: "Keyboard Navigation" },
              { name: "Screen Readers" },
              { name: "Accessibility Testing Tools" },
            ],
          },
          {
            name: "Web Development Tools",
            subtopics: [
              {
                name: "Version Control",
                subtopics: [
                  { name: "Git" },
                  { name: "Subversion (SVN)" },
                  { name: "Mercurial" },
                ],
              },
              {
                name: "Text Editors",
                subtopics: [
                  { name: "VS Code" },
                  { name: "Sublime Text" },
                  { name: "Atom" },
                  { name: "Vim" },
                  { name: "Emacs" },
                ],
              },
              {
                name: "Package Managers",
                subtopics: [
                  { name: "npm" },
                  { name: "Yarn" },
                  { name: "pip" },
                  { name: "composer" },
                ],
              },
              {
                name: "Bundlers",
                subtopics: [
                  { name: "Webpack" },
                  { name: "Rollup" },
                  { name: "Parcel" },
                ],
              },
              {
                name: "Transpilers",
                subtopics: [{ name: "Babel" }, { name: "TypeScript" }],
              },
              {
                name: "Task Runners",
                subtopics: [{ name: "Grunt" }, { name: "Gulp" }],
              },
              {
                name: "Debugging Tools",
                subtopics: [
                  { name: "Chrome DevTools" },
                  { name: "Firefox Developer Tools" },
                  { name: "Safari Web Inspector" },
                ],
              },
              {
                name: "Testing Frameworks",
                subtopics: [
                  { name: "Jest" },
                  { name: "Mocha" },
                  { name: "Jasmine" },
                  { name: "Chai" },
                  { name: "Enzyme" },
                ],
              },
              {
                name: "Continuous Integration/Continuous Deployment Tools",
                subtopics: [
                  { name: "Jenkins" },
                  { name: "Travis CI" },
                  { name: "CircleCI" },
                  { name: "GitHub Actions" },
                ],
              },
              {
                name: "Containerization",
                subtopics: [
                  { name: "Docker" },
                  { name: "Kubernetes" },
                  { name: "OpenShift" },
                ],
              },
            ],
          },
        ],
      },
      {
        name: "Artificial Intelligence",
        subtopics: [
          { name: "Machine Learning" },
          { name: "Deep Learning" },
          { name: "Neural Networks" },
          { name: "Natural Language Processing" },
          { name: "Computer Vision" },
          { name: "Reinforcement Learning" },
          { name: "Artificial Intelligence Tools" },
        ],
      },
      {
        name: "Data Science",
        subtopics: [
          { name: "Data Analysis" },
          { name: "Data Visualization" },
          { name: "Data Mining" },
          { name: "Statistical Modeling" },
          { name: "Big Data Frameworks" },
          { name: "Data Storage and Processing" },
          { name: "Data Science and Big Data Tools" },
        ],
      },
      {
        name: "Computer Networking",
        subtopics: [
          { name: "Network Protocols" },
          { name: "Network Architecture" },
          { name: "Routing and Switching" },
          { name: "Network Security" },
          { name: "Wireless Networking" },
          { name: "Network Monitoring and Troubleshooting" },
        ],
      },
      {
        name: "Cybersecurity",
        subtopics: [
          { name: "Network Security" },
          { name: "Application Security" },
          { name: "Cryptography" },
          { name: "Penetration Testing" },
          { name: "Security Auditing" },
          { name: "Incident Response" },
        ],
      },
      {
        name: "Cloud Computing",
        subtopics: [
          { name: "AWS" },
          { name: "Azure" },
          { name: "Google Cloud Platform" },
          { name: "Serverless Computing" },
          { name: "Containerization" },
          { name: "Microservices" },
        ],
      },
      {
        name: "Operating Systems",
        subtopics: [
          { name: "Windows" },
          { name: "macOS" },
          { name: "Linux" },
          { name: "UNIX" },
          { name: "Mobile Operating Systems" },
        ],
      },
      {
        name: "Software Engineering",
        subtopics: [
          { name: "Software Development Methodologies" },
          { name: "Software Testing" },
          { name: "User Interface (UI) and User Experience (UX) Design" },
          { name: "IT Management and Support" },
          { name: "Blockchain and Cryptocurrency" },
        ],
      },
      {
        name: "Computer Hardware",
        subtopics: [
          { name: "Processors and Architectures" },
          { name: "Memory and Storage" },
          { name: "Peripherals and Interfaces" },
          { name: "Power Supplies and Cooling" },
          { name: "Networking Hardware" },
          { name: "Computer Assembly and Troubleshooting" },
        ],
      },
      {
        name: "Software Tools and IDEs",
        subtopics: [
          { name: "Visual Studio" },
          { name: "IntelliJ IDEA" },
          { name: "PyCharm" },
          { name: "Eclipse" },
          { name: "Xcode" },
          { name: "Atom" },
          { name: "VSCode" },
        ],
      },
      {
        name: "Other Topics",
        subtopics: [
          { name: "Robotics" },
          { name: "Artificial Life" },
          { name: "Computer Graphics" },
          { name: "Scientific Computing" },
          { name: "Game Development" },
        ],
      },
    ],
  },
  {
    name: "Education",
    subtopics: [
      { name: "Early Childhood Education" },
      { name: "K-12 Education" },
      { name: "Higher Education" },
      { name: "Special Education" },
      { name: "Educational Technology" },
      { name: "Teaching Methods" },
    ],
  },
  {
    name: "Engineering",
    subtopics: [
      { name: "Civil Engineering" },
      { name: "Mechanical Engineering" },
      { name: "Electrical Engineering" },
      { name: "Chemical Engineering" },
      { name: "Aerospace Engineering" },
      { name: "Biomedical Engineering" },
    ],
  },
  {
    name: "Health and Medicine",
    subtopics: [
      { name: "Medical Specialties" },
      { name: "Nursing" },
      { name: "Pharmacy" },
      { name: "Dentistry" },
      { name: "Public Health" },
      { name: "Nutrition and Dietetics" },
    ],
  },
  {
    name: "Law",
    subtopics: [
      { name: "Criminal Law" },
      { name: "Civil Law" },
      { name: "Intellectual Property" },
      { name: "Family Law" },
      { name: "Contract Law" },
      { name: "International Law" },
    ],
  },
  {
    name: "Mathematics",
    subtopics: [
      { name: "Algebra" },
      { name: "Geometry" },
      { name: "Calculus" },
      { name: "Probability and Statistics" },
      { name: "Applied Mathematics" },
      { name: "Discrete Mathematics" },
    ],
  },
  {
    name: "Natural Sciences",
    subtopics: [
      { name: "Biology" },
      { name: "Chemistry" },
      { name: "Physics" },
      { name: "Earth Science" },
      { name: "Astronomy" },
      { name: "Environmental Science" },
    ],
  },
  {
    name: "Social Sciences",
    subtopics: [
      { name: "Anthropology" },
      { name: "Economics" },
      { name: "Political Science" },
      { name: "Psychology" },
      { name: "Sociology" },
      { name: "Human Geography" },
    ],
  },
  {
    name: "Technology",
    subtopics: [
      { name: "Electronics" },
      { name: "Robotics" },
      { name: "Nanotechnology" },
      { name: "Biotechnology" },
      { name: "Renewable Energy" },
      { name: "Telecommunications" },
    ],
  },
  {
    name: "Vocational Skills",
    subtopics: [
      { name: "Automotive Repair" },
      { name: "Plumbing" },
      { name: "Carpentry" },
      { name: "Welding" },
      { name: "Culinary Arts" },
      { name: "Horticulture" },
    ],
  },
];

export const getFlatTopics = (topics: Topic[], parent = ""): string[] => {
  let flatTopics: any[] = [];

  for (const topic of topics) {
    const path = parent ? `${parent}/${topic.name}` : topic.name;
    flatTopics.push(path);

    if (topic.subtopics) {
      flatTopics = flatTopics.concat(getFlatTopics(topic.subtopics, path));
    }
  }

  return flatTopics;
};

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas (the)",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory (the)",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands (the)",
  "Central African Republic (the)",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands (the)",
  "Colombia",
  "Comoros (the)",
  "Congo (the Democratic Republic of the)",
  "Congo (the)",
  "Cook Islands (the)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic (the)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (the) [Malvinas]",
  "Faroe Islands (the)",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories (the)",
  "Gabon",
  "Gambia (the)",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (the)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic (the)",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands (the)",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (the Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands (the)",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger (the)",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands (the)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines (the)",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation (the)",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan (the)",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands (the)",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates (the)",
  "United Kingdom of Great Britain and Northern Ireland (the)",
  "United States Minor Outlying Islands (the)",
  "United States of America (the)",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
];

export const languages = [
  "Abkhaz",
  "Afar",
  "Afrikaans",
  "Akan",
  "Albanian",
  "Amharic",
  "Arabic",
  "Aragonese",
  "Armenian",
  "Assamese",
  "Avaric",
  "Avestan",
  "Aymara",
  "Azerbaijani",
  "Bambara",
  "Bashkir",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bihari",
  "Bislama",
  "Bosnian",
  "Breton",
  "Bulgarian",
  "Burmese",
  "Catalan; Valencian",
  "Chamorro",
  "Chechen",
  "Chichewa; Chewa; Nyanja",
  "Chinese",
  "Chuvash",
  "Cornish",
  "Corsican",
  "Cree",
  "Croatian",
  "Czech",
  "Danish",
  "Divehi; Dhivehi; Maldivian;",
  "Dutch",
  "English",
  "Esperanto",
  "Estonian",
  "Ewe",
  "Faroese",
  "Fijian",
  "Finnish",
  "French",
  "Fula; Fulah; Pulaar; Pular",
  "Galician",
  "Georgian",
  "German",
  "Greek, Modern",
  "Guaraní",
  "Gujarati",
  "Haitian; Haitian Creole",
  "Hausa",
  "Hebrew (modern)",
  "Herero",
  "Hindi",
  "Hiri Motu",
  "Hungarian",
  "Interlingua",
  "Indonesian",
  "Interlingue",
  "Irish",
  "Igbo",
  "Inupiaq",
  "Ido",
  "Icelandic",
  "Italian",
  "Inuktitut",
  "Japanese",
  "Javanese",
  "Kalaallisut, Greenlandic",
  "Kannada",
  "Kanuri",
  "Kashmiri",
  "Kazakh",
  "Khmer",
  "Kikuyu, Gikuyu",
  "Kinyarwanda",
  "Kirghiz, Kyrgyz",
  "Komi",
  "Kongo",
  "Korean",
  "Kurdish",
  "Kwanyama, Kuanyama",
  "Latin",
  "Luxembourgish, Letzeburgesch",
  "Luganda",
  "Limburgish, Limburgan, Limburger",
  "Lingala",
  "Lao",
  "Lithuanian",
  "Luba-Katanga",
  "Latvian",
  "Manx",
  "Macedonian",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Māori",
  "Marathi (Marāṭhī)",
  "Marshallese",
  "Mongolian",
  "Nauru",
  "Navajo, Navaho",
  "Norwegian Bokmål",
  "North Ndebele",
  "Nepali",
  "Ndonga",
  "Norwegian Nynorsk",
  "Norwegian",
  "Nuosu",
  "South Ndebele",
  "Occitan",
  "Ojibwe, Ojibwa",
  "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic",
  "Oromo",
  "Oriya",
  "Ossetian, Ossetic",
  "Panjabi, Punjabi",
  "Pāli",
  "Persian",
  "Polish",
  "Pashto, Pushto",
  "Portuguese",
  "Quechua",
  "Romansh",
  "Kirundi",
  "Romanian, Moldavian, Moldovan",
  "Russian",
  "Sanskrit (Saṁskṛta)",
  "Sardinian",
  "Sindhi",
  "Northern Sami",
  "Samoan",
  "Sango",
  "Serbian",
  "Scottish Gaelic; Gaelic",
  "Shona",
  "Sinhala, Sinhalese",
  "Slovak",
  "Slovene",
  "Somali",
  "Southern Sotho",
  "Spanish; Castilian",
  "Sundanese",
  "Swahili",
  "Swati",
  "Swedish",
  "Tamil",
  "Telugu",
  "Tajik",
  "Thai",
  "Tigrinya",
  "Tibetan Standard, Tibetan, Central",
  "Turkmen",
  "Tagalog",
  "Tswana",
  "Tonga (Tonga Islands)",
  "Turkish",
  "Tsonga",
  "Tatar",
  "Twi",
  "Tahitian",
  "Uighur, Uyghur",
  "Ukrainian",
  "Urdu",
  "Uzbek",
  "Venda",
  "Vietnamese",
  "Volapük",
  "Walloon",
  "Welsh",
  "Wolof",
  "Western Frisian",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zhuang, Chuang",
];

export const skills = [
  "Accounting",
  "Advertising",
  "Aerospace",
  "Agriculture",
  "Architecture",
  "Banking",
  "Technology",
  "Other",
  "Utilities",
  "UX Design",
  "UI Design",
  "Product Design",
  "Research",
  "Programming",
];
